# treefmt configuration file
# See https://github.com/numtide/treefmt

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.json", "*.jsonc", "*.yaml", "*.yml", "*.md"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
