name: Version

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create version tag
        uses: googleapis/release-please-action@v5
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
